[tool.poetry]
name = "pygame-lesson"
version = "0.1.0"
description = ""
authors = ["ivan.akulinichev"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pygame = "^2.6.1"
mypy = "^1.13.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
